@startuml


abstract class Personas {
	#class_db db
	#int person
	#String apellido
	#String nombre
	#Array<Documentos> documento
	#Array<Emails> email
	#Array<Telefonos> telefono
	#Array<Direcciones> direccion
	#File foto_persona
	#Calendar fechaNacimiento
	#String estadoCivil
	#String nacionalidad
	#String tipoNacionalidad
	#String sexo
	
	#String esposa
	#String familiarACargo
	#String F
	
	
	+String getNombreYApellido()
}


class Dnis [[java:personas.Dnis]] {
	-int numero
}
abstract class Documentos [[java:personas.Documentos]] {
	-String tipo
}
class Emails [[java:personas.Emails]] {
	-String tipo
	-String email
}
class Cuentas [[java:personas.Cuentas]] {
	-int idCuenta
	-String cuenta
	-String emailCuenta
	-String[] tipoCuenta
	-String fraseDeSeguridad
	-Calendar vencimiento
	-Calendar alta
	-Calendar baja
}
class Academicos [[java:personas.Academicos]] {
}
class Telefonos [[java:personas.Telefonos]] {
	-String tipo
	-int numero
	-int codArea
	-int codPais
}
class Externo [[java:personas.Externo]] {
}
abstract class Empleados [[java:personas.Empleados]] {
	#int legajo
	#Calendar fechaIngreso
	#Calendar fechaBaja
	#Calendar fechaReingreso
	#Calendar inicioCargo
	#String actividad
	#int antiguedad
	#String cajaDeAhorro
	#String cajaJubilacion
	#String cargo
	#int codigoAlta
	#String titulo
	#int codigoTitulo
	#int nroJubilacion
	#int nroSindicato
	#String obraSocial
	#int redito
	#String seguro
	#int sucursalCtaBanco
	#int tipoCtaBanco
	#String unidadContrato
	#String tipoBco
	
}
class Docentes [[java:personas.Docentes]] {
}
class Pasaportes [[java:personas.Pasaportes]] {
	-String numero
}
class Cuils [[java:personas.Cuils]] {
	-int numero
	+boolean verificar()
}
class Documentos [[java:personas.Documentos]] {
}
class Alumnos [[java:personas.Alumnos]] {
}
class Listados [[java:personas.Listados]] {
	+void listarPerson()
	+void listarPersonFacu()
	+void buscarAppers()
	+void buscarPerson()
	+void buscarPerdoc()
	+void buscarTargeta()
	+void buscarUsuarioWeb()
	+void buscarCatXPerson()
}
class Administrativos [[java:personas.Administrativos]] {
}
class Empleados [[java:personas.Empleados]] {
}
class Direcciones {
	-class_db db
	-int tipo
	-String calle
	-int numero
	-int piso
	-String departamento
	-String pais
	-String poldiv
	-String city
	-String codigoPostal
	
	+void recuperar_dire_person()
	+void grabar_direccion()
	-void cargar_db_apers()
	+String getPais_hf()
	+String getTipo_hf()
	+String getPoldiv_hf()
	+String getCity_hf()
}

Documentos <|-- Dnis
Documentos <|-- Pasaportes
Documentos <|-- Cuils
Personas <|-- Alumnos
Personas <|-- Externo
Personas <|-- Empleados
Empleados <|-- Administrativos
Empleados <|-- Academicos
Empleados <|-- Docentes
Personas --> "1" Cuentas : cuenta

Personas "1" *-- "*" Documentos
Personas "1" *-- "*" Direcciones
Personas "1" *-- "*" Telefonos
Personas "1" *-- "*" Emails
Personas "1" *-- "1" Cuentas

@enduml